save = "raw-data"
halo-mass = "3.19e+09"
scale-radius = "1.39e+00"
falloff-factor = "1.04e+01"
cutoff-factor = "2.07e+01"
profile = "nfw"
nparticles = 1734
tfinal = 391
ntimesteps = 782000
nout = 100
dtwrite = 7821
master-seed = 42
tidalf-file = "params/nsphere_galacticus_lr_tuning__alpha_0.50020260218_203955/tidalf/tidalf_12461.bin"
