save = "raw-data"
halo-mass = "2.26e+09"
scale-radius = "1.54e+00"
falloff-factor = "7.87e+00"
cutoff-factor = "1.57e+01"
profile = "nfw"
nparticles = 5075
tfinal = 296
ntimesteps = 592000
nout = 100
dtwrite = 5921
master-seed = 42
tidalf-file = "params/nsphere_galacticus_lr_tuning__alpha_0.30020260218_203702/tidalf/tidalf_3762.bin"
