save = "raw-data"
halo-mass = "2.83e+09"
scale-radius = "2.04e+00"
falloff-factor = "4.01e+00"
cutoff-factor = "8.02e+00"
profile = "nfw"
nparticles = 76683
tfinal = 275
ntimesteps = 550000
nout = 100
dtwrite = 5501
master-seed = 42
tidalf-file = "params/nsphere_galacticus_lr_tuning__alpha_0.30020260218_203702/tidalf/tidalf_3375.bin"
