save = "raw-data"
halo-mass = "1.18e+09"
scale-radius = "1.45e+00"
falloff-factor = "3.87e+00"
cutoff-factor = "7.75e+00"
profile = "nfw"
nparticles = 2286
tfinal = 301
ntimesteps = 602000
nout = 100
dtwrite = 6021
master-seed = 42
tidalf-file = "params/nsphere_galacticus_lr_tuning__alpha_0.30020260218_203702/tidalf/tidalf_5583.bin"
