save = "raw-data"
halo-mass = "2.58e+09"
scale-radius = "2.23e+00"
falloff-factor = "3.99e+00"
cutoff-factor = "7.98e+00"
profile = "nfw"
nparticles = 84748
tfinal = 221
ntimesteps = 442000
nout = 100
dtwrite = 4421
master-seed = 42
tidalf-file = "params/nsphere_galacticus_lr_tuning__alpha_0.55020260218_204040/tidalf/tidalf_6378.bin"
