save = "raw-data"
halo-mass = "3.22e+09"
scale-radius = "1.67e+00"
falloff-factor = "3.82e+00"
cutoff-factor = "7.63e+00"
profile = "nfw"
nparticles = 22941
tfinal = 423
ntimesteps = 846000
nout = 100
dtwrite = 8461
master-seed = 42
tidalf-file = "params/nsphere_galacticus_lr_tuning__alpha_0.55020260218_204040/tidalf/tidalf_2678.bin"
