save = "raw-data"
halo-mass = "2.00e+09"
scale-radius = "2.01e+00"
falloff-factor = "3.78e+00"
cutoff-factor = "7.57e+00"
profile = "nfw"
nparticles = 23600
tfinal = 232
ntimesteps = 464000
nout = 100
dtwrite = 4641
master-seed = 42
tidalf-file = "params/nsphere_galacticus_lr_tuning__alpha_0.40020260218_203829/tidalf/tidalf_1666.bin"
