save = "raw-data"
halo-mass = "1.49e+09"
scale-radius = "1.35e+00"
falloff-factor = "4.70e+00"
cutoff-factor = "9.40e+00"
profile = "nfw"
nparticles = 43135
tfinal = 375
ntimesteps = 750000
nout = 100
dtwrite = 7501
master-seed = 42
tidalf-file = "params/nsphere_galacticus_lr_tuning__alpha_0.35020260218_203745/tidalf/tidalf_1945.bin"
