save = "raw-data"
halo-mass = "1.16e+09"
scale-radius = "1.16e+00"
falloff-factor = "4.16e+00"
cutoff-factor = "8.32e+00"
profile = "nfw"
nparticles = 3548
tfinal = 430
ntimesteps = 860000
nout = 100
dtwrite = 8601
master-seed = 42
tidalf-file = "params/nsphere_galacticus_lr_tuning__alpha_0.60020260218_204124/tidalf/tidalf_10101.bin"
